package platform

// Code generated by TestAggregateSpeedResults at 2026-06-18 16:59:45; 
// 该文件通过聚合 test_output/speed_results*.csv 生成，用于提供额外精选测速 URL。

var fastSpeedTestURLs = []string{
        "https://cachefly.cachefly.net/300mb.test", // avg: 4161.72 KB/s, samples: 4, errors: 0
        "https://awscli.amazonaws.com/AWSCLIV2.msi", // avg: 3845.64 KB/s, samples: 4, errors: 0
        "https://updates.cdn-apple.com/2025FallFCS/fullrestores/089-12066/4F86CB11-E6FA-47CB-96A8-527A4CBD9273/iPhone18,3_26.1_23B85_Restore.ipsw", // avg: 2841.51 KB/s, samples: 3, errors: 1
        "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.0-linux-x86_64.tar.gz", // avg: 2764.00 KB/s, samples: 3, errors: 1
        "https://hkg.download.datapacket.com/1000mb.bin", // avg: 2668.24 KB/s, samples: 3, errors: 1
        "https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe", // avg: 2266.21 KB/s, samples: 3, errors: 1
        "https://hnd-jp-ping.vultr.com/vultr.com.1000MB.bin", // avg: 2142.98 KB/s, samples: 3, errors: 1
        "https://sgp.download.datapacket.com/1000mb.bin", // avg: 2104.47 KB/s, samples: 4, errors: 0
        "https://fra-de-ping.vultr.com/vultr.com.1000MB.bin", // avg: 1638.43 KB/s, samples: 4, errors: 0
        "https://get.enterprisedb.com/postgresql/postgresql-16.3-1-windows-x64.exe", // avg: 1635.80 KB/s, samples: 4, errors: 0
        "https://tyo.download.datapacket.com/1000mb.bin", // avg: 1588.26 KB/s, samples: 4, errors: 0
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.42.06_linux.run", // avg: 1452.09 KB/s, samples: 4, errors: 0
        "https://ash.download.datapacket.com/1000mb.bin", // avg: 1370.03 KB/s, samples: 4, errors: 0
        "https://download.blender.org/release/Blender4.3/blender-4.3.0-windows-x64.zip", // avg: 1310.14 KB/s, samples: 4, errors: 0
        "https://nodejs.org/dist/v22.13.1/node-v22.13.1-x64.msi", // avg: 1304.24 KB/s, samples: 3, errors: 1
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.85_windows.exe", // avg: 1281.99 KB/s, samples: 4, errors: 0
        "https://hil.proof.ovh.us/files/1Gb.dat", // avg: 1142.27 KB/s, samples: 4, errors: 0
        "https://lax-ca-us-ping.vultr.com/vultr.com.1000MB.bin", // avg: 1106.75 KB/s, samples: 4, errors: 0
        "https://par.download.datapacket.com/1000mb.bin", // avg: 1105.33 KB/s, samples: 4, errors: 0
        "https://sgp.proof.ovh.net/files/1Gb.dat", // avg: 1096.30 KB/s, samples: 4, errors: 0
        "https://ash-speed.hetzner.com/1GB.bin", // avg: 1092.94 KB/s, samples: 4, errors: 0
        "https://download.blender.org/release/Blender4.3/blender-4.3.0-linux-x64.tar.xz", // avg: 1046.28 KB/s, samples: 4, errors: 0
}
