package platform

// Code generated by TestAggregateSpeedResults at 2026-04-01 12:26:00; 
// 该文件通过聚合 test_output/speed_results*.csv 生成，用于提供额外精选测速 URL。

var fastSpeedTestURLs = []string{
        "https://updates.cdn-apple.com/2025FallFCS/fullrestores/089-12066/4F86CB11-E6FA-47CB-96A8-527A4CBD9273/iPhone18,3_26.1_23B85_Restore.ipsw", // avg: 6920.43 KB/s, samples: 23, errors: 8
        "https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe", // avg: 5528.35 KB/s, samples: 19, errors: 11
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.42.06_linux.run", // avg: 2850.35 KB/s, samples: 16, errors: 14
        "https://update.code.visualstudio.com/1.102.0/win32-x64-user/stable", // avg: 2503.55 KB/s, samples: 24, errors: 8
        "https://nodejs.org/dist/v22.13.1/node-v22.13.1-x64.msi", // avg: 2405.01 KB/s, samples: 27, errors: 4
        "http://sgp.download.datapacket.com/100mb.bin", // avg: 2266.60 KB/s, samples: 27, errors: 5
        "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.0-linux-x86_64.tar.gz", // avg: 1914.17 KB/s, samples: 28, errors: 4
        "http://lax.download.datapacket.com/10000mb.bin", // avg: 1887.13 KB/s, samples: 25, errors: 6
        "https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.5.0esr/win64/en-US/Firefox%20Setup%20140.5.0esr.exe", // avg: 1759.49 KB/s, samples: 23, errors: 7
        "https://awscli.amazonaws.com/AWSCLIV2.msi", // avg: 1734.52 KB/s, samples: 23, errors: 7
        "https://download-installer.cdn.mozilla.net/pub/firefox/releases/145.0/win64/en-US/Firefox%20Setup%20145.0.exe", // avg: 1732.94 KB/s, samples: 27, errors: 4
        "http://tyo.download.datapacket.com/100mb.bin", // avg: 1719.05 KB/s, samples: 27, errors: 5
        "https://sgp.proof.ovh.net/files/1Gb.dat", // avg: 1525.27 KB/s, samples: 26, errors: 6
        "http://hkg.download.datapacket.com/1000mb.bin", // avg: 1419.22 KB/s, samples: 25, errors: 7
        "https://cachefly.cachefly.net/300mb.test", // avg: 1400.21 KB/s, samples: 24, errors: 7
        "https://download.blender.org/release/Blender4.3/blender-4.3.0-linux-x64.tar.xz", // avg: 1195.00 KB/s, samples: 25, errors: 5
        "http://ash.download.datapacket.com/100mb.bin", // avg: 1176.79 KB/s, samples: 25, errors: 6
        "https://download.gimp.org/mirror/pub/gimp/v3.0/windows/gimp-3.0.0-setup.exe", // avg: 1062.33 KB/s, samples: 16, errors: 14
}
