name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: false
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Check existing release
        id: check_release
        run: |
          if gh release view ${{ github.ref_name }} &> /dev/null; then
            echo "release_exists=true" >> $GITHUB_OUTPUT
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete existing release
        if: steps.check_release.outputs.release_exists == 'true'
        run: |
          gh release delete ${{ github.ref_name }} --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: false

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=match,pattern=^v?(.*-(?:beta|alpha|rc|dev|snapshot).*?)$,group=1,enable=${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc') || contains(github.ref_name, 'dev') || contains(github.ref_name, 'snapshot') }}

            type=match,pattern=^v?(.*)$,group=1,enable=${{ !(contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc') || contains(github.ref_name, 'dev') || contains(github.ref_name, 'snapshot')) }}
          flavor: |
            latest=${{ !(contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc') || contains(github.ref_name, 'dev') || contains(github.ref_name, 'snapshot')) }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            VERSION=${{ github.ref_name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=高性能[测活、测速、媒体检测]代理检测筛选工具，支持100-1000高并发低占用运行，大幅减少数倍检测时间。

  notify: # Telegram 通知
    runs-on: ubuntu-latest
    needs: [releaser, docker] # 依赖前两个 job，确保成功后运行
    steps:
      - name: Determine Notification Title
        id: meta
        run: |
          TAG_NAME="${{ github.ref_name }}"
          # 使用正则匹配常见的预发布后缀 (忽略大小写)
          if [[ "$TAG_NAME" =~ (beta|alpha|rc|dev|snapshot|dev|test) ]]; then
            echo "title=🚧 *subs-check-pro 预发布*" >> $GITHUB_OUTPUT
          else
            echo "title=🚀 *subs-check-pro 更新*" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ${{ steps.meta.outputs.title }}

            版本: `${{ github.ref_name }}`
            项目: `${{ github.repository }}`

            说明:
              - 修复 Gemini 解锁检测不准确，支持欧盟区标签显示
              - 添加 Copilot 解锁检测
              - WebUI 为列表添加拖拽排序
              - WebUI 可视化分析报告优化,添加订阅成功率实时筛选
              - 移动设备现在可以折叠日志显示
              - 节点状态通知添加"消耗流量"数据
              - 支持 HTTP/2, 优化连接复用逻辑
              - 支持单独设置媒体解锁超时
              - 错误修复和优化
              
            🔗 [查看详情](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }})
